name: Juejin Auto Check in

on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * *"

jobs:
  juejin-check-in:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm install
    - run: export cookie="${{secrets.JUEJIN_COOKIE}}"
    - run: npm run juejin
